// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDNGuginHdZst137D5SerlmCEhz1Gqbs-M",
    authDomain: "headstart-34da7.firebaseapp.com",
    projectId: "headstart-34da7",
    storageBucket: "headstart-34da7.firebasestorage.app",
    messagingSenderId: "436796327887",
    appId: "1:436796327887:web:870360fa7077e62d8d34ba",
    measurementId: "G-EWS0VTR9W1",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALTf1-xWUBwVjCVP-OgS49uOB03Fw_sAM',
    appId: '1:676566799863:android:e3f3cec3516d41955fcaf2',
    projectId: "cube360-9f1a0",
    storageBucket: "cube360-9f1a0.firebasestorage.app",
    messagingSenderId: '676566799863',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBdEA7ARVdvIHVOv2lYWcPrLRtWOyVT9j8",
    appId: "1:676566799863:ios:e3f3cec3516d41955fcaf2",
    projectId: "cube360-9f1a0",
    storageBucket: "cube360-9f1a0.firebasestorage.app",
    messagingSenderId: "676566799863",
    iosBundleId: 'com.gdsc.cube360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJuBLguPpwBP6Nn4K718FWki7sMlAmscs',
    appId: '1:287727538614:ios:a09f09086b7e5ed1963117',
    messagingSenderId: '287727538614',
    projectId: 'worldchat-fc10f',
    storageBucket: 'worldchat-fc10f.appspot.com',
    iosBundleId: 'com.example.worldchat.RunnerTests',
  );
}
